# dev environment（生产环境）
server:
  port: 8123
  servlet:
    context-path: /api
    # cookie 7 天过期
    session:
      cookie:
        max-age: 604800
  tomcat:
    max-connections: 1000
    accept-count: 100
    connection-timeout: 20000
spring:
  application:
    name: agent-application-creator
  # 文件上传设置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai  # 统一Jackson序列化时区（东八区）
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xiaorui_app_creator?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
  # Session 配置
  session:
    redis:
      namespace: "xiaorui:session" # 定义存储在 Redis 中的 session 数据的命名空间
      flush-mode: on_save  # 每次保存或更新 session 时立即将数据同步到 Redis
      save-mode: always  # 每次请求结束时都保存 session
  # 邮箱配置
  mail:
    username: 368649957@qq.com
    password: ozxbkjocwsaicbag  # 邮箱授权码
    host: smtp.qq.com  # SMTP服务器地址
    port: 465  # SMTP服务器端口
  security:
    user:
      name: xiaorui
      password: 123456
  # Redis 配置
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 3
      # Redis 密码，如果有的话
      #password: 123456
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 16
          max-idle: 16
          min-idle: 4
          max-wait: 3000ms
        shutdown-timeout: 200ms
    # MongoDB 配置
    mongodb:
      host: 127.0.0.1
      port: 27017
      #password: 123456
      uri: mongodb://127.0.0.1:27017
      database: agent_memory_store  # 自定义数据库
  # AI 配置
  ai:
    dashscope:
      api-key: sk-b1aea9f904d6478db3fa8bf439a1a460  # 阿里云百炼
      chat:
        # 这里的配置其实在阿里云百炼的智能体应用控制台中也配置了，看情况是否需要
        options:
          model: "qwen3-coder-plus"  # 这里就使用 通义千问3-Coder-Plus
          stream: true
          incremental-output: true  # 开启增量输出
          temperature: 0.1  # 设置在 0.1 至 0.3 之间，以减少生成结果的随机性。

# springdoc-openapi（4 版本的 knife4j 接口文档依赖于 springdoc）
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.xiaorui.agentapplicationcreator.controller
# knife4j 接口文档
knife4j:
  enable: true
  setting:
    language: zh_cn
# minio 配置
minio:
  endpoint: http://172.30.43.12:9000  # minio服务器API地址（linux）
  access-key: xiaorui   # minio服务器用户名
  secret-key: 18656412886ty   # minio服务器密码
  default-bucket: agent-app-creator-bucket  # 创建的 bucket 名称
# sftp 配置
sftp:
  host: 172.30.43.12  # Linux服务器IP
  port: 22  # SFTP端口（默认22）
  username: shenrui   # 服务器用户名
  password: 18656412886ty   # 服务器密码